export interface IUser {
  _id?: string; // Optional - will be auto-generated by MongoDB
 username: string;
  email?: string;
  password?: string;
  phone?: string;
  createdAt?: Date;
  updatedAt?: Date;
}